# XOR 구현:

Multiple Layer Perceptron을 사용하여 XOR를 구현하기<br>
activation function: 사용안함<br>
XOR 모델을 class 형태로 구현할 것<br>
Train 함수를 구현할 것<br>
훈련된 XOR 모델을 통해 y를 출력하여, XOR gate의 출력을 만족하는지 확인하시오.<br>
            * y가 0.5 이상은 1, 반대는 0으로 산출할 것

In [348]:
import torch
from torch import nn

In [349]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
Y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float)

In [350]:
class XOR_Model(nn.Module):
    def __init__(self):
        super(XOR_Model, self).__init__()
        self.hidden_layer = nn.Linear(2, 4)
        self.output_layer = nn.Linear(4, 1)

    def forward(self, x):
        x = self.hidden_layer(x)
        x = self.output_layer(x)
        return x

In [351]:
def train(model, X, Y):
    loss_fn = nn.MSELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.02)

    epochs=9000
    for epoch in range(1, epochs + 1):
        optimizer.zero_grad()
        hypothesis = model(X)
        loss = loss_fn(hypothesis, Y)
        loss.backward()
        optimizer.step()

        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item()}')


In [352]:
# 데이터 및 모델 초기화
model = XOR_Model()

In [353]:
train(model, X, Y)

Epoch: 1000, Loss: 0.25000184774398804
Epoch: 2000, Loss: 0.25
Epoch: 3000, Loss: 0.25
Epoch: 4000, Loss: 0.2499999701976776
Epoch: 5000, Loss: 0.2499999701976776
Epoch: 6000, Loss: 0.2499999701976776
Epoch: 7000, Loss: 0.2499999701976776
Epoch: 8000, Loss: 0.2499999701976776
Epoch: 9000, Loss: 0.2499999701976776


In [354]:
# 훈련된 모델로 XOR 출력 확인
def predict(x, model):
    with torch.no_grad():
        output = model(x)
        if output.item() >= 0.5:
            return 1
        else:
            return 0

In [355]:
def calculate_accuracy(model, X_test, Y_test):
    correct = 0
    total = 0
    with torch.no_grad():
        for x, y in zip(X_test, Y_test):
            prediction = predict(x, model=model)
            if prediction == y.item():
                correct += 1
            total += 1
    accuracy = correct / total
    return accuracy

# 테스트 데이터에 대한 정확도 계산
accuracy = calculate_accuracy(model, X, Y)
print(f'테스트 데이터 정확도: {accuracy}')

테스트 데이터 정확도: 0.75


In [356]:
print("XOR 구현")
for x in X:
    print(x, model(x).item(),predict(x, model=model))

XOR 구현
tensor([0., 0.]) 0.5000021457672119 1
tensor([0., 1.]) 0.5000000596046448 1
tensor([1., 0.]) 0.5000002384185791 1
tensor([1., 1.]) 0.4999980330467224 0
